#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

java -jar wacc-42-compiler.jar $@
arm-linux-gnueabi-gcc -mcpu=arm1176jzf-s -mtune=arm1176jzf-s -c waccyruntime/runtime.c -o waccyruntime/runtime.o
exit $?

