#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

# make
java -jar wacc-42-compiler.jar $@
STATUS=$?
exit $STATUS

