#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

./compile $@
STATUS=$?
if [ $STATUS -eq 0 ]; then
  arm-linux-gnueabi-gcc -mcpu=arm1176jzf-s -mtune=arm1176jzf-s secret.o $(basename $@ .wacc).s string.o -o $(basename $@ .wacc)
  qemu-arm -L /usr/arm-linux-gnueabi/ $(basename $@ .wacc)
fi
exit $STATUS